# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'InstaPhoto' do
    pod 'AFNetworking', '~> 2.0'
end

target 'InstaPhotoTests' do

end

target 'InstaPhotoUITests' do

end

