# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'InstaPhotoSwift' do
    # TODO: will this need to be available in testing?
    pod 'Alamofire', '~> 2.0'
end

target 'InstaPhotoSwiftTests' do

end

target 'InstaPhotoSwiftUITests' do

end

